name: AnimalsArrow
author: DarkBow_
version: 0.1
main: fr.darkbow_.animalsarrow.AnimalsArrow
api-version: 1.16
depend:
  - ProtocolLib
commands:
  animalsarrow:
    description: Manage the Animals Arrow Plugin
    permission:
    aliases: [aa, animalsa, arrowanimals, aarrow]